{{ if .Values.kibanaIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kibana
  annotations:
    {{ if .Values.kibanaIngress.annotations }}
    {{ toYaml .Values.kibanaIngress.annotations | nindent 4 }}
    {{ end }}
spec:
  rules:
    - host: {{ .Values.kibanaIngress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-kibana-kb-http
                port:
                  number: 5601
  tls:
    - hosts:
        - {{ .Values.kibanaIngress.host }}
      secretName: {{ .Values.kibanaIngress.tlsSecretName }}
{{ end }}
{{ if .Values.elasticsearchIngress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-es
  annotations:
    {{ if .Values.elasticsearchIngress.annotations }}
    {{ toYaml .Values.elasticsearchIngress.annotations | nindent 4 }}
    {{ end }}
spec:
  rules:
    - host: {{ .Values.elasticsearchIngress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elasticsearch-es-http
                port:
                  number: 9200
  tls:
    - hosts:
        - {{ .Values.elasticsearchIngress.host }}
      secretName: {{ .Values.elasticsearchIngress.tlsSecretName }}
{{ end }}
