serivceMonitor:
  labels:
    release: kube-prometheus-stack
services:
  namespace: kube-system
prometheusRule:
  labels:
    release: kube-prometheus-stack
  rules:
  - alert: PromHTTPRequestErrors
    expr: (sum(rate(promhttp_metric_handler_requests_total{job="calico-node",code=~"(4|5).."}[5m] offset 5m )) by (instance, job, cluster, host) / sum(rate(promhttp_metric_handler_requests_total{job="calico-node"}[5m] offset 5m )) by (instance, job, cluster, host)) * 100 > 1
    for: 10m
    labels:
      severity: info
      type: calico-node
    annotations:
      description: "Cluster {{ $labels.cluster }}: HTTP requests errors on host {{ $labels.host }}."
      summary: Calico HTTP requests errors on cluster {{ $labels.cluster }}
  - alert: CalicoDatapaneFailuresHigh
    expr: increase(felix_int_dataplane_failures[1h] offset 5m) > 5
    for: 1h
    labels:
      severity: warning
      type: calico-node
    annotations:
      description: 'Felix cluster {{ $labels.cluster }} has seen {{ $value }} dataplane failures within the last hour'
      summary: 'A high number of dataplane failures within Felix are happening'
  - alert: CalicoIpsetErrorsHigh
    expr: increase(felix_ipset_errors[1h] offset 5m) > 5
    for: 1h
    labels:
      severity: warning
      type: calico-node
    annotations:
      description: 'Felix cluster {{ $labels.cluster }} has seen {{ $value }} ipset errors within the last hour'
      summary: 'A high number of ipset errors within Felix are happening'
  - alert: CalicoIptableSaveErrorsHigh
    expr: increase(felix_iptables_save_errors[1h] offset 5m) > 5
    for: 1h
    labels:
      severity: warning
      type: calico-node
    annotations:
      description: 'Felix cluster {{ $labels.cluster }} has seen {{ $value }} iptable save errors within the last hour'
      summary: 'A high number of iptable save errors within Felix are happening'
  - alert: CalicoIptableRestoreErrorsHigh
    expr: increase(felix_iptables_restore_errors[1h] offset 5m) > 5
    for: 1h
    labels:
      severity: warning
      type: calico-node
    annotations:
      description: 'Felix cluster {{ $labels.cluster }} has seen {{ $value }} iptable restore errors within the last hour'
      summary: 'A high number of iptable restore errors within Felix are happening'
