apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- .Values.serivceMonitor.labels| toYaml | nindent 4 }}
  name: calico
spec:
  endpoints:
  - port: metrics-port
    relabelings:
    - sourceLabels:
      - __meta_kubernetes_endpoint_node_name
      targetLabel: instance
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchExpressions:
    - key: k8s-app
      operator: In
      values: [ "calico-felix", "calico-kube-controllers" ]