apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: calico-felix
  name: felix-metrics-svc
  namespace: {{ .Values.services.namespace }}
spec:
  clusterIP: None
  ports:
  - name: metrics-port
    port: 9091
  selector:
    k8s-app: calico-node
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: calico-kube-controllers
  name: calico-kube-controllers-metrics-svc
  namespace: {{ .Values.services.namespace }}
spec:
  clusterIP: None
  ports:
  - name: metrics-port
    port: 9094
  selector:
    k8s-app: calico-kube-controllers