apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: kube-prometheus-stack
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: kube-prometheus-stack
    repoURL: https://github.com/NeorCloud/neor-demo-ba1-compute1-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - Prune=true
    - SelfHeal=true
    - ServerSideApply=true
