apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logs-collection
  namespace: argocd
spec:
  destination:
    namespace: logs-collection
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: logs-collection
    repoURL: https://github.com/NeorCloud/neor-demo-ba1-compute1-cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    - Prune=true
    - SelfHeal=true
